// packages/react-view3d/src/View3D.tsx
/*
 * Copyright (c) 2020 NAVER Corp.
 * egjs projects are licensed under the MIT license
 */
import * as React from "react";
import VanillaView3D, {
  View3DOptions,
  withMethods,
  EVENTS,
  DEFAULT_CLASS
} from "@egjs/view3d";

import { View3DProps } from "./types";

type View3DPropsAndOptions = Partial<View3DProps & View3DOptions>;

const view3DSetterNames = Object.getOwnPropertyNames(VanillaView3D.prototype)
  .filter(name => {
    const descriptor = Object.getOwnPropertyDescriptor(VanillaView3D.prototype, name);

    if (name.startsWith("_")) return false;
    if (descriptor?.value) return false;

    return !!descriptor!.set;
  });

class View3D extends React.PureComponent<View3DPropsAndOptions> {
  public static defaultProps: Partial<View3DProps> = {
    tag: "div"
  };

  private _vanillaView3D: VanillaView3D;
  private _containerEl: HTMLElement;

  public get view3D() { return this._vanillaView3D; }
  public get element() { return this._containerEl; }

  public constructor(props: View3DPropsAndOptions) {
    super(props);

    withMethods(this, "_vanillaView3D");
  }

  public componentDidMount() {
    this._vanillaView3D = new VanillaView3D(
      this._containerEl,
      this.props
    );

    this._bindEvents();
  }

  public componentWillUnmount() {
    this._vanillaView3D.destroy();
  }

  public componentDidUpdate(prevProps) {
    const view3D = this._vanillaView3D;

    view3DSetterNames.forEach(name => {
      const oldProp = prevProps[name];
      const newProp = this.props[name];

      if (newProp !== oldProp) {
        view3D[name] = newProp;
      }
    });
  }

  public render() {
    const {
      tag,
      className = "",
      canvasClass = "",
      ...restProps
    } = this.props;
    const Container = tag as any;

    const wrapperClassName = `${DEFAULT_CLASS.WRAPPER} ${className}`.trim();
    const canvasClassName = `${DEFAULT_CLASS.CANVAS} ${canvasClass}`.trim();

    const attributes: { [key: string]: any } = {};

    for (const name in restProps) {
      if (!(name.startsWith("on")) && !(name in VanillaView3D.prototype)) {
        attributes[name] = restProps[name];
      }
    }

    return <Container {...attributes} className={wrapperClassName} ref={(e?: HTMLElement) => {
      e && (this._containerEl = e);
    }}>
      <canvas className={canvasClassName} />
      { this.props.children }
    </Container>;
  }

  private _bindEvents() {
    const view3D = this._vanillaView3D;

    Object.keys(EVENTS).forEach((eventKey: keyof typeof EVENTS) => {
      const eventName = EVENTS[eventKey];
      const propName = `on${eventName.charAt(0).toUpperCase() + eventName.slice(1)}`;

      view3D.on(eventName, e => {
        e.target = this;

        const evtHandler = this.props[propName];
        if (evtHandler) {
          evtHandler(e);
        }
      });
    });
  }
}

interface View3D extends React.Component<View3DPropsAndOptions>, VanillaView3D {}
export default View3D;

// packages/svelte-view3d/src/View3D.svelte
<script lang="ts">
  import {
    onMount,
    onDestroy,
    createEventDispatcher
  } from "svelte";
  import VanillaView3D, {
    EVENTS,
    DEFAULT_CLASS
  } from "@egjs/view3d";

  // @ts-ignore
  __DECLARE_PROPS__

  const dispatch = createEventDispatcher();
  const view3DOptionNames = Object.getOwnPropertyNames(VanillaView3D.prototype)
    .filter(name => {
      const descriptor = Object.getOwnPropertyDescriptor(VanillaView3D.prototype, name);

      if (name.startsWith("_")) return false;
      if (descriptor?.value) return false;

      return true;
    });

  const view3DSetterNames = view3DOptionNames.filter(name => {
    const descriptor = Object.getOwnPropertyDescriptor(VanillaView3D.prototype, name);

    return !!descriptor!.set;
  });

  export let canvasClass: string = "";
  export let view3D: VanillaView3D | null = null;
  let containerEl: HTMLElement;
  let prevProps = getSetterProps();

  $: wrapperClass = `${DEFAULT_CLASS.WRAPPER} ${$$props.class ?? ""}`.trim();
  $: canvasClass = `${DEFAULT_CLASS.CANVAS} ${$$props.canvasClass ?? ""}`.trim();

  // On props change
  $: {
    if (view3D) {
      view3DSetterNames.forEach(name => {
        const oldProp = prevProps[name];
        const newProp = $$props[name];

        if (newProp !== oldProp) {
          view3D![name] = newProp;
        }
      });
      prevProps = getSetterProps();
    }
  }

  onDestroy(() => {
    view3D?.destroy();
  });

  onMount(() => {
    view3D = new VanillaView3D(containerEl, $$props);

    Object.keys(EVENTS).forEach(key => {
      const eventName = EVENTS[key];

      view3D!.on(eventName, e => {
        dispatch(eventName, e);
      });
    });
  });

  export function getElement() {
    return containerEl;
  }

  function getSetterProps() {
    return view3DSetterNames.reduce((props, name) => {
      props[name] = $$props[name];

      return props;
    }, {});
  }
</script>

<svelte:options accessors={true} />
<div bind:this={containerEl} {...$$restProps} class={wrapperClass}>
  <canvas class={canvasClass}></canvas>
  <slot />
</div>
