// packages/vue3-view3d/demo/components/Event.vue
<template>
  <View3D
    src="https://naver.github.io/egjs-view3d/model/draco/alarm.glb"
    class="view3d-3by1"
    @ready="this.onReady"
  />
</template>
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  methods: {
    onReady: evt => {
      console.log("ready", evt);
    }
  }
})
</script>
<style>

</style>

// packages/ngx-view3d/projects/demo/src/app/event/event.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "demo-event",
  templateUrl: "./event.component.html",
  styleUrls: ["../app.component.css", "./event.component.css"]
})
export class EventComponent {
  public onReady(evt) {
    console.log("ready", evt);
  }
}

<ngx-view3d
  class="view3d-3by1"
  [options]="{ src: 'https://naver.github.io/egjs-view3d/model/cube.glb' }"
  (ready)="onReady($event)"
></ngx-view3d>
