// packages/ngx-view3d/projects/demo/src/app/plugin/plugin.component.ts
import { Component } from "@angular/core";
import { ControlBar, LoadingBar } from "../../../../ngx-view3d/src/public-api";

@Component({
  selector: "demo-plugin",
  templateUrl: "./plugin.component.html",
  styleUrls: ["../app.component.css"]
})
export class PluginComponent {
  public src = "https://naver.github.io/egjs-view3d/model/RobotExpressive.glb";
  public plugins = [new LoadingBar(), new ControlBar()];
}

<ngx-view3d
  class="view3d-3by1"
  [src]="src"
  [plugins]="plugins"
></ngx-view3d>

// packages/vue3-view3d/demo/components/Plugin.vue
<template>
  <View3D
    src="https://naver.github.io/egjs-view3d/model/RobotExpressive.glb"
    class="view3d-3by1"
    :plugins="this.plugins"
  />
</template>
<script lang="ts">
import { defineComponent } from "vue";
import { ControlBar, LoadingBar } from "../../src";

export default defineComponent({
  data() {
    return {
      plugins: [new LoadingBar(), new ControlBar()]
    }
  }
})
</script>
<style>

</style>
