// packages/svelte-view3d/demo/components/PropChange.svelte
<script lang="ts">
  import View3D from "../../src";

  let skybox: string | null = null;

  function onClick() {
    if (!skybox) {
        skybox = "https://naver.github.io/egjs-view3d/texture/venice_sunset_1k.hdr";
      } else {
        skybox = null;
      }
  }
</script>

<View3D
  src="https://naver.github.io/egjs-view3d/model/draco/alarm.glb"
  class="view3d-3by1"
  skybox={skybox}
/>
<button on:click={onClick}>Change Skybox</button>

// packages/vue3-view3d/demo/components/PropChange.vue
<template>
  <div>
    <View3D
      ref="view3d"
      src="https://naver.github.io/egjs-view3d/model/draco/alarm.glb"
      :skybox="this.skybox"
      class="view3d-3by1"
    />
    <button @click="this.onClick">Change Skybox</button>
  </div>
</template>
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  data() {
    return {
      skybox: null
    }
  },
  methods: {
    onClick: function() {
      if (!this.skybox) {
        this.skybox = "https://naver.github.io/egjs-view3d/texture/venice_sunset_1k.hdr";
      } else {
        this.skybox = null;
      }
    }
  }
})
</script>
<style>

</style>
