// packages/svelte-view3d/demo/components/PropChange.svelte
<script lang="ts">
  import View3D from "../../src";

  let skybox: string | null = null;

  function onClick() {
    if (!skybox) {
        skybox = "https://naver.github.io/egjs-view3d/texture/venice_sunset_1k.hdr";
      } else {
        skybox = null;
      }
  }
</script>

<View3D
  src="https://naver.github.io/egjs-view3d/model/draco/alarm.glb"
  class="view3d-3by1"
  skybox={skybox}
/>
<button on:click={onClick}>Change Skybox</button>

// packages/ngx-view3d/projects/demo/src/app/prop-change/prop-change.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "demo-prop-change",
  templateUrl: "./prop-change.component.html",
  styleUrls: ["../app.component.css"]
})
export class PropChangeComponent {
  public src = "https://naver.github.io/egjs-view3d/model/draco/alarm.glb";
  public skybox: string | null = null;

  public onClick() {
    this.skybox = this.skybox ? null : "https://naver.github.io/egjs-view3d/texture/venice_sunset_1k.hdr"
  }
}

<ngx-view3d
  class="view3d-3by1"
  [src]="src"
  [skybox]="skybox"
></ngx-view3d>
<button (click)="onClick()">Change Skybox</button>
