// packages/svelte-view3d/demo/components/Annotation.svelte
<script lang="ts">
  import View3D from "../../src";
</script>

<View3D
  src="https://naver.github.io/egjs-view3d/model/draco/payphone.glb"
  class="view3d-3by1"
>
  <div class="view3d-annotation-wrapper">
    <div class="view3d-annotation default" data-position="0.13 0.5 -0.05" data-focus="-90 0 30"></div>
    <div class="view3d-annotation default" data-position="-0.22 0.5 0.05" data-focus="90 0 30" data-duration="500"></div>
    <div class="view3d-annotation default" data-position="-0.05 0.4 0.18" data-focus="0 20 35" data-duration="0"></div>
  </div>
</View3D>

// packages/ngx-view3d/projects/demo/src/app/annotation/annotation.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "demo-annotation",
  templateUrl: "./annotation.component.html",
  styleUrls: ["../app.component.css"]
})
export class AnnotationComponent {

}

<ngx-view3d
  class="view3d-3by1"
  [src]="'https://naver.github.io/egjs-view3d/model/draco/payphone.glb'"
>
  <div class="view3d-annotation-wrapper">
    <div class="view3d-annotation default" data-position="0.13 0.5 -0.05" data-focus="-90 0 30"></div>
    <div class="view3d-annotation default" data-position="-0.22 0.5 0.05" data-focus="90 0 30" data-duration="500"></div>
    <div class="view3d-annotation default" data-position="-0.05 0.4 0.18" data-focus="0 20 35" data-duration="0"></div>
  </div>
</ngx-view3d>
