// packages/vue-view3d/demo/components/Method.vue
<template>
  <div>
    <View3D
      ref="view3d"
      src="https://naver.github.io/egjs-view3d/model/RobotExpressive.glb"
      class="view3d-3by1"
      @ready="this.onReady"
    />
    <button @click="this.onClick">Change Animation</button>
  </div>
</template>
<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  methods: {
    onReady: evt => {
      evt.target.animator.play(1);
    },
    onClick: function() {
      this.$refs.view3d.animator.play(2);
    }
  }
})
</script>
<style>

</style>

// packages/svelte-view3d/demo/components/Method.svelte
<script lang="ts">
  import View3D from "../../src";

  let view3D: View3D;

  function onReady(evt) {
    evt.detail.target.animator.play(1);
  }

  function onClick() {
    view3D.animator.play(2);
  }
</script>

<View3D
  bind:this={view3D}
  src="https://naver.github.io/egjs-view3d/model/RobotExpressive.glb"
  class="view3d-3by1"
  on:ready={onReady}
  canvasClass="some-other-canvas"
/>
<button on:click={onClick}>Change Animation</button>
