// packages/ngx-view3d/projects/demo/src/app/method/method.component.ts
import { Component, ViewChild } from "@angular/core";

@Component({
  selector: "demo-method",
  templateUrl: "./method.component.html",
  styleUrls: ["../app.component.css"]
})
export class MethodComponent {
  @ViewChild("viewer") public view3D;

  public onReady(evt) {
    evt.target.animator.play(1);
  }

  public onClick() {
    this.view3D.animator.play(2);
  }
}

<div>
  <ngx-view3d
    #viewer
    class="view3d-3by1"
    [options]="{ src: 'https://naver.github.io/egjs-view3d/model/RobotExpressive.glb' }"
    (ready)="onReady($event)"
  ></ngx-view3d>
  <button (click)="onClick()">Change Animation</button>
</div>

// packages/vue-view3d/demo/components/Method.vue
<template>
  <div>
    <View3D
      ref="view3d"
      src="https://naver.github.io/egjs-view3d/model/RobotExpressive.glb"
      class="view3d-3by1"
      @ready="this.onReady"
    />
    <button @click="this.onClick">Change Animation</button>
  </div>
</template>
<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  methods: {
    onReady: evt => {
      evt.target.animator.play(1);
    },
    onClick: function() {
      this.$refs.view3d.animator.play(2);
    }
  }
})
</script>
<style>

</style>
